#docker run --name new-api-solid-pg -e POSTGRESQL_USERNAME=docker -e POSTGRESQL_PASSWORD=docker -e POSTGRESQL_DATABASE=apisolid -p 5430:5432 bitnami/postgresql



version: '3'

services: 
  new-api-solid-pg
    image: bitnami/postgresql
    ports: 
      - 5430:5432
      environment:
        - POSTGRESQL_USERNAME=docker
        - POSTGRESQL_PASSWORD=docker
        - POSTGRESQL_DATABASE=apisolid
